# Generated by Django 4.2.15 on 2025-06-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_make_perspective_name_required"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("member", "question")},
        ),
    ]
