# Generated by Django 4.2.15 on 2025-06-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_add_unique_constraint_answer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together=set(),
        ),
    ]
