# Generated by Django 4.2.15 on 2025-06-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0002_add_discrepancy_models"),
        ("labels", "0018_change_discrepancy_to_project"),
    ]

    operations = []
