# Generated by Django 4.2.15 on 2025-06-16 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0008_assignment"),
        ("labels", "0020_annotationdiscrepancy_discrepancytype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discrepancymessage",
            name="example",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discrepancy_messages",
                to="examples.example",
            ),
        ),
    ]
